# @package _global_
approach: multi_table

tables:
  - name: subjects
    primary_key: ${data.subject_column}
    tabular_model_configuration:
      max_epochs: 1

  - name: sequences
    foreign_keys:
      - column: ${data.subject_column}
        referenced_table: subjects
        is_context: true
    tabular_model_configuration:
      max_sequence_length: 15
      model:  ${training.model}
      max_epochs:  ${training.max_epochs}
      max_training_time:  ${training.max_training_time}
      batch_size:  ${training.batch_size}
      gradient_accumulation_steps:  ${training.gradient_accumulation_steps}
      enable_flexible_generation: false
      # differential_privacy: ${privacy}
      # rare_category_replacement_method: null #SAMPLE

