defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled 

# Common settings
random_seed: 42

# MLflow settings  
mlflow:
  tracking_uri: null
  experiment_name: "mostlyai_challenge"
  enable_system_metrics: true
  registry_uri: null
